Repository 7kms/km7-kit, pull requests merged in 2020-02, with the labels that each got.

#1 initial versions
  .github/verifyCommitMsg
  .gitignore
  lerna.json
  package-lock.json
  package.json
  packages/babel-preset-km7/package-lock.json
  packages/babel-preset-km7/package.json
  packages/eslint-config-km7/package-lock.json
  packages/eslint-config-km7/package.json
  packages/km7-utils/package-lock.json
  packages/km7-utils/package.json
  packages/km7/README.md
  packages/km7/package-lock.json
  packages/km7/package.json
  packages/km7/templates/projects/web-backend/tsconfig.json
  scripts/publish.js
  tsconfig.json
Labels: pr(internal)

#2 publish脚本错误
  package-lock.json
  package.json
  packages/babel-preset-km7/package-lock.json
  packages/babel-preset-km7/package.json
  packages/eslint-config-km7/package-lock.json
  packages/eslint-config-km7/package.json
  packages/km7-utils/package-lock.json
  packages/km7-utils/package.json
  packages/km7/README.md
  packages/km7/package-lock.json
  packages/km7/package.json
  scripts/publish.js
  scripts/utils.js
  scripts/utils.spec.ts
Labels: pr(bug)

#3 Fix config
  .gitignore
  lerna.json
Labels: pr(chore)

#4 fix: cli params parse
  packages/km7/src/cli.ts
Labels: pr(bug)

#5 chore: correct km7 version
  packages/km7/package.json
Labels: pr(chore)

#6 fix: fix template name
  packages/km7/package-lock.json
  packages/km7/src/cli.ts
  packages/km7/src/generate.ts
Labels: pr(bug)
